create table leaved_users
(
    id               serial NOT NULL,
    user_seq         integer not null,
    email            text                                                    not null,
    password         text                                                    not null,
    role             text                                                    not null,
    created_at       timestamp with time zone                                not null,
    leaved_at        timestamp with time zone                                not null default now(),
    activated        boolean                                                 not null,
    activate_token   varchar,
    forgot_token     varchar,
    name             varchar,
    day              varchar,
    month            varchar,
    year             varchar,
    gender           varchar,
    phone1           varchar,
    phone2           varchar,
    phone3           varchar,
    user_id          varchar,
    ci               varchar,
    sms_send_agree   boolean      default false                              not null,
    email_send_agree boolean      default false                              not null,
    business_confirm boolean,
    address          text,
    type             varchar(255) default 'individual'::character varying    not null,
    file             varchar,
    business_number  varchar,
    company_name     varchar,
    file_name        varchar
);